FORMAT: 1A

# PMO_Msia

API to get information on law, politicians, government of Malaysia.  
The end goal of this project is to enable people to build apps related to the administration

# PMO API Root [/]

The top level ..

# Group Party 

Resources related to Political parties ..

## Party TEST [/parties/]

### List All Political Parties [GET]

+ Response 200 (application/json)

        [
            {
                "resource": "/parties/DAP/1"
            },
            {
                "resource": "/parties/PKR/2"
            }
        ]

